### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by mickepe** [Atvaark/W3SavegameEditor#1]
Very nice to see someone working on this. Thanks to a friend I got a compiled version of this. After commenting out the bit that crashed the program I get a quite empty window with a couple of input fields.
![window](https://cloud.githubusercontent.com/assets/14888723/11627162/bb0fce4a-9ce8-11e5-8cf2-0d883cd313b8.jpg)
This looks a bit cryptic, should it look like that? Could you give a short description of how you intended it to be used? 

Thanks!

**Comment by Atvaark** [comment]
It should look like that if you don't have any savegames in the default location.

Since you didn't write what caused the crash I can only guess you removed the part that looks up the savegames.

Try using the [binaries that I released](https://github.com/Atvaark/W3SavegameEditor/releases/tag/v0.1.1) and post the error.

**Comment by mickepe** [comment]
Thank you Atvaark! Your build works. Now for the next step, is there a way of decompressing a save and recompressing it again? Right now there are only fields for the Info Variables that change when you click on the different saves. No amount of right-clicking or trying different keyboard combinations seemed to do anything.

**Comment by Atvaark** [comment]
Sorry for the silence. I haven't continued working on the editing and exporting features since analyzing all value types was too time consuming for me and the format was regularly changed at that time.

**Comment by mickepe** [comment]
No worries! I found some console commands that did the trick for me. Thanks for your work though!
