### ISSUE TITLE
Doesn't start....

### ISSUE THREAD

**Issue by zetagame** [Atvaark/W3SavegameEditor#2]
Firstly, thank you for taking the time to build this, you're a boss. My experience may just be due to noobness. Tried building/running newest version in windows 8, also tried running source of 0.1.1, no dice. I can see the parser and decryption in visual studio, but actually running the build exe doesn't do anything, and I don't know enough C# to execute it in a command line. Know any good places I could teach myself just enough for this specific task?

**Comment by Atvaark** [comment]
You should only need to install.NET Framework v4.5 to run it, which should be pre-installed on Windows 8.
Does your event log have any crash reports when you run it?

**Comment by zetagame** [comment]
Nope. It never opens, just get the loading circle until either explorer.exe crashes and restarts itself or until I close the window I tried to open it from. Also, Thank you for replying!!!!

**Comment by Atvaark** [comment]
I can't think of a reason why running it would crash your windows explorer.
Does your windows event viewer log anything about W3SavegameEditor.exe crashing?

**Comment by zetagame** [comment]
Nope. Like I said, it never fully opens so there's no log of it crashing. Is there any chance I could convince you to edit a few things in my save game in exchange for my full cooperation in helping debug this issue? Might be down to help with building it out too, I have over a decade of experience with UX and UI/design

**Comment by Atvaark** [comment]
Enabling the developer console would probably be easier depending on what you want to do.

Thanks for the offer, but most of the unfinished work in this project is analyzing hundreds of different datatypes at binary level. Something I neither have the patience nor motivation for at the moment.

What I originally wanted to use is some UI component that can display the thousands of variables in a tree while still being fast. The current solution takes quite some time to display all the nodes. I don't know if such a component exists free of charge.
