### ISSUE TITLE
Save file format

### ISSUE THREAD

**Issue by solusipse** [Atvaark/W3SavegameEditor#4]
First of all, thank you for this tool - reading it's source was a huge help for finding out how Witcher's save files were compressed.
I wanted to make a simple inventory editor but unfortunately encountered some difficulties. I've rewritten some parts of your application in C (https://github.com/solusipse/witcher3-inventory-editor, for now it's only capable of decompressing save files), but can't get pass this point:

```
private void ReadFooter(BinaryReader reader)
{
    reader.BaseStream.Seek(-6, SeekOrigin.End);
    VariableTableOffset = reader.ReadInt32();
    StringTableFooterOffset = VariableTableOffset - 10;
```

When I'm calculating `StringTableFooterOffset` for the decompressed file, it gives me random offsets. 

When I try to read values from there:

```
    reader.BaseStream.Position = StringTableFooterOffset;
    NmSectionOffset = reader.ReadInt32();
    RbSectionOffset = reader.ReadInt32();
```

I usually get something that is far greater that total file length.
So, I'd like to ask if maybe something has changed with patch 1.20 and this algorithm is not compatibile with recent savegames anymore, or, maybe, I don't understand how it works and it's just my fault that I can't reproduce a working mechanism? (Btw I never wrote a single line in C#.)

**Comment by Atvaark** [comment]
Hey,

like you already said it's most likely a change in the save game format. I stopped working on this project when patch 1.08.3 was released in last August.

If you want to make your own tool you should familiarize yourself with some binary format reversing and see what changed in the format. I could provide you with an old savegame that this tool can still parse.

**Comment by solusipse** [comment]
Thank you. Yes, please, that would be awesome.

**Comment by Atvaark** [comment]
See this for an 1.08 savegame:
[gamesaves.zip](https://github.com/Atvaark/W3SavegameEditor/files/301085/gamesaves.zip)

My tools seems to open the 1.21 save just fine by the way.

**Comment by solusipse** [comment]
Thank you very much! I'm afraid I don't get something right. Sorry for troubling you but, damn, I have no clue why my procedure fails and it makes me anxious. May I have one additional question, do you mind?

So there's the whole procedure:
This is how last 10 bytes of your save file look like after decompression:

```
... 97 CA 03 00 32 5F 9E 00 53 45
```

Let's move our reader there:

```
reader.BaseStream.Seek(-6, SeekOrigin.End);
```

so we are at:

```
32 5F 9E 00 53 45
```

We save next 4 bytes (`32 5F 9E 00`) to `VariableTableOffset`:

```
VariableTableOffset = reader.ReadInt32();
```

Since it's little endian it's equal to: `0x9e5f32`. We also save value to `StringTableFooterOffset` with:

```
StringTableFooterOffset = VariableTableOffset - 10;
```

so it's equal to: `0x9e5f28`. Let's go to that address:

```
reader.BaseStream.Position = StringTableFooterOffset;
```

and read 4 bytes from there to:

```
NmSectionOffset = reader.ReadInt32();
```

But it's sensless, we're at 

```
... 6B 5F 65 6D 68 79 72 5F 66 6F 72 5F 68 65 6C 70
... k  _  e  m  h  y  r  _  f  o  r  _  h  e  l  p
```

So, it's definitely not an address of the NM section. Could you, please, show me where my understanding of your code fails?

**Comment by Atvaark** [comment]
You're off by the size of the ChunkedLz4FileHeader. 

If you subtract 0x00000c0c from 0x9E5F28 you'll get to the position behind the string ENOD.

```
9E:5300h: 6C 67 11 67 77 69 6E 74 5F 63 61 72 64 5F 77 79  lg.gwint_card_wy 
9E:5310h: 76 65 72 6E 00 00 00 00 45 4E 4F 44 8F 94 9A 00  vern....ENOD
```

The offset after ENOD will point to the string table header (NMMANU).

```
9A:8880h: 93 9A 00 4E 4D 4D 41 4E 55 8A 36 00 00 00 00 00  “š.NMMANUŠ6..... 
9A:8890h: 00 06 45 6E 74 69 74 79 02 6E 50 06 55 69 6E 74  ..Entity.nP.Uint 
```

**Comment by solusipse** [comment]
Damn, I didn't include lz4 header in my output file, now it works perfectly. Thank you very much!

**Comment by Atvaark** [comment]
You're welcome.
